### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by chandrashekhar-racharla** [ankurk91/vue-loading-overlay#10]
Not working on IE11. it is giving syntax error in utils.js

**Comment by ankurk91** [comment]
Okay, will check

**Comment by ankurk91** [comment]
@chandrashekhar-racharla
It is already mentioned in README that this plugin is intended to be used in modern browser only.
Even though, I tried online IE emulators but none of them worked for me.

I have limited access to Windows machine, i use MacOS on work and Linux at home.

Can you share the exact error you see in console ?
Can you also share a screenshot of that.
Thanks.

**Comment by chandrashekhar-racharla** [comment]
just giving **syntax error** message.If I click on it it will goes to utils.js file

**Comment by ankurk91** [comment]
There is no **utils.js** file in this package.
It does have a **util.js** file.
https://github.com/ankurk91/vue-loading-overlay/blob/master/src/js/util.js but it should not be used by webpack.
webpack should be using this file from **dist** folder
https://unpkg.com/vue-loading-overlay@2.1.0/dist/vue-loading.js
This is a standalone file and it does not link back to any of js files.

**Comment by chandrashekhar-racharla** [comment]
inside the Component.vue using  import {removeElement, hasWindow, HTMLElement} from './util'.that cause the problem.
Please correct me if my understanding is wrong

**Comment by ankurk91** [comment]
How are you using this component?

You are not suggested to use the **src** folder.
Please install it via npm, you will see a **dist** folder.

If you are using webpack or laravel-mix then
```
import Loading from 'vue-loading-overlay';
```
should be ok, it will pick from **dist** folder.

I can not help you unless you you tell me about your platform.

**Comment by chandrashekhar-racharla** [comment]
Thanks for pointing me correct path .Now issue fixed 
thank you very much for your support
