### ISSUE TITLE
Blur (Backdrop-Filter) not working

### ISSUE THREAD

**Issue by danielDigitalArt** [ankurk91/vue-loading-overlay#101]
**I'm submitting a ...**  (check one with "x")

```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* Vue.js version : 3.2.31
* Browser name and version : Chrome(100.0.4896.88)|Edge (100.0.1185.44)|Firefox (FF does not support backdrop-filter yet)
* This package version : 5.0.3

**Current behavior**
The Blur Option does not work (does not blur anything)

**Expected behavior**
Content behind the background should be blured

**Minimal reproduction of the problem with instructions**
Using default settings will already show that the background does not get blured, also additional options do not blur anything. The problem lies in the css setting of "opacity: 0.5" this does make the background div transparent but backdrop-filter does not work with the opacity value. A fix is to use "background: rgba(255,255,255,0.5) instead of "background: #FFF; opacity: 0.5". Then the blur does worl correctly.
Currently i added an addistional sass file which does these settings here:
```css
.vld-parent{
    .vld-background{
        background: rgba(136,136,136,0.5) !important;
        opacity: 1 !important;
    }
}
```
So i get a grey background which is transparent with the blur working as it should.

Also maybe it would be wise to have different options for the opacity, where one is for the icon and one for the background.

**Comment by ankurk91** [comment]
Something might have broken during vue 2 to 3 upgrade.

I will check soon

**Comment by ankurk91** [comment]
The blur feature was taken from

https://bootstrap-vue.org/docs/components/overlay#overlay-backdrop-color

**Comment by danielDigitalArt** [comment]
Maybe it was removed in a Webkit Update, when i look at the Page, it also does not show the blur effect:
![image](https://user-images.githubusercontent.com/25100967/164218041-b00287f1-d478-4723-a343-0c440231e6cd.png)

When i modfify it in the developer console it works:
![image](https://user-images.githubusercontent.com/25100967/164218257-98a83af7-acf8-468c-90f6-9ad9b5501b0e.png)
![image](https://user-images.githubusercontent.com/25100967/164218343-6ca29ede-2ac0-42a4-9a6d-1f1085ee63aa.png)

**Comment by ankurk91** [comment]
Thanks for update, i will look into it soon

**Comment by ankurk91** [comment]
You can make the blur effect working with a combination of these 3 props, see example:

```js
let loader = this.$loading.show({    
        backgroundColor: 'rgba(136,136,136,0.1)',     
        opacity: 1,
        blur: '2px'
      });
```

**Comment by danielDigitalArt** [comment]
Good that it can be worked around like that, question is if it would make sense to implement this into the component itself so it can set the values correctly internally, so that current users do not have to change their code.

Also there is a difference on this approach and the expected behavior from before, as now it sets the opacity to 1, the loader icon is not transparent anymore, thus it might be better to implement the change here into the component itself, as it can set the opacity of the icon to "0.1" and the overlay to opacity 1 but with background-color using the opacity value supplied as a property.

This would surely require a calculation from the standard css value "#888" to its corresponding rgb value. This could be difficult, as the component would also have to check which version the color was supplied to it, for example [#888, #888888, #88888819, rgb(136,136,136), rgba(136,136,136,0.1)]

**Comment by ankurk91** [comment]
It would be better to remove the blur feature, and let developer to style it.

**Comment by ankurk91** [comment]
The buggy prop has been removed in v6
