### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by nazaninhesari** [ankurk91/vue-loading-overlay#11]
not work in vue.2.5 i use method plugin

**Comment by ankurk91** [comment]
What is not working??
I think you should say "not working in my project".
Can you reproduce it here
https://jsfiddle.net/ankurk91/w8y8k5wo/

**Comment by nazaninhesari** [comment]
excuse me . i not  import css.
do it can work just in div ?? not full screen ?

**Comment by ankurk91** [comment]
It can work for a specific div.
see how -
https://github.com/ankurk91/vue-loading-overlay/blob/master/examples/App.vue

**html**
https://github.com/ankurk91/vue-loading-overlay/blob/d4c26a2d218771fb70acb7eb3fc99fc6db0bffcd/examples/App.vue#L15-L17
**js**
https://github.com/ankurk91/vue-loading-overlay/blob/d4c26a2d218771fb70acb7eb3fc99fc6db0bffcd/examples/App.vue#L58-L64
