### ISSUE TITLE
Why opacity option is not working

### ISSUE THREAD

**Issue by wjdrbs96** [ankurk91/vue-loading-overlay#110]
**I'm submitting a ...**  (check one with "x")

```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```

**Tell about your platform**

* Vue.js version : 2.5.16
* Browser name and version : Chrome
* This package version : 5.x.x

```
npm install vue-loading-overlay@^3.0 
```

3.0 version installed successfully.

<br>

**Current behavior**

```js
        <div class="vld-parent">
           <loading :active.sync="isLoading"
                   :can-cancel="false"
                   :width="128"
                   :height="128"
                   :opacity="opacity"
                   :background-color="bgColor"
                   :loader='loader'
                   :color="'#1E90FF'"
                   :is-full-page="fullPage"></loading>
        <div>
```

- isLoading: false,
- fullPage: true,
- loader: 'spinner',
- opacity: 0.1,           
- bgColor: '#ffffff',

The background is not blurred when loading is in progress.

<br>

**Expected behavior**

https://ankurk91.github.io/vue-loading-overlay/

I want the background to be blurred when loading is in progress as it works on the link above. 

I thought I could adjust the opacity value, but it doesn't work as I want, so I don't know what I did wrong.

**Minimal reproduction of the problem with instructions**

Thanks.

**Comment by ankurk91** [comment]
Opacity is working fine for me
https://jsfiddle.net/zdesr0mo/

For background blur read this issue
https://github.com/ankurk91/vue-loading-overlay/issues/101

**Comment by ankurk91** [comment]
Have you read the linked issue?

**Comment by wjdrbs96** [comment]
> It would be better to remove the blur feature, and let developer to style it.

I didn't read it properly. I'm sorry. I checked. Thank you.
