### ISSUE TITLE
vue3-loading-overlay error after build and deploy to vps

### ISSUE THREAD

**Issue by wangphun** [ankurk91/vue-loading-overlay#112]
Hi everyone, i am making an loading overlay and it works perfectly in local, but after build with `npm run build` , have error with hide() function. `r.ctx.hide()` is not a function. 
- i am using `vue3-loading-overlay` with 
```
<script setup lang="ts">. 
`const submit = async (userName?: string, accountStatus?: boolean) => {
  let loader = useLoading();
  loader.show({
    // Optional parameters
    container: fullPage ? null : formContainer.value,
    loader: "bars",
    canCancel: true,
    onCancel: onCancel,
  });
  await axios.post(url, xxx);
  await initTabulator();
  loader.hide(); // fine with local but not prod
};`
```

**Comment by ankurk91** [comment]
You mentioned that the package name is "vue3-loading-overlay" but your are reporting the issue on "vue-loading-overlay " repo.
Report your issue here instead
https://github.com/moyoujun/vue3-loading-overlay
