### ISSUE TITLE
A plugin must either be a function or an object with an "install" function

### ISSUE THREAD

**Issue by sevenmay** [ankurk91/vue-loading-overlay#113]
**I'm submitting a ...**  (check one with "x")

```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* Vue.js version : 3.2.45
* This package version : 6.0.2

**Current behavior**

Can't install the plugin.

**Expected behavior**

That the plugin installation works

---

![image](https://user-images.githubusercontent.com/1004551/216304389-b6647389-ef10-43d6-bc68-a70769b0d5ef.png)

This doesn't work anymore.

```
const LoadingPlugin = (app, props = {}, slots = {}) => {
  const instance = useLoading(props, slots);
  app.config.globalProperties.$loading = instance;
  app.provide('$loading', instance)
};
```

See vue docs: [https://vuejs.org/guide/reusability/plugins.html#writing-a-plugin](https://vuejs.org/guide/reusability/plugins.html#writing-a-plugin)

```
const LoadingPlugin = {
  install(app, options) {
    // ...
  }
};
```

Thanks!

**Comment by ankurk91** [comment]
The documentation says
```
A plugin is defined as either an object that exposes an install() method, or simply a function that acts as the install function itself. 
```

**Comment by ankurk91** [comment]
I dont see anything broken
https://jsfiddle.net/ankurk91/2ou37bc8/

Hope you are importing the plugin like this, version 6 uses named imports

```js
import {LoadingPlugin} from 'vue-loading-overlay';

// create app code goes here

app.use(LoadingPlugin)
```

**Comment by sevenmay** [comment]
> Hope you are importing the plugin like this, version 6 uses named imports

Yes
```
import {LoadingPlugin} from 'vue-loading-overlay';
```

It works with Vue 3.2.35 but not with Vue 3.2.45.

It's very strange. I created a plugin (TestPlugin) like yours without problem, but LoadingPlugin doesn't works.

[https://stackblitz.com/edit/vue-ljlzhx?file=src%2Fmain.js](https://stackblitz.com/edit/vue-ljlzhx?file=src%2Fmain.js)

You can see the warning in the console.

```
const TestPlugin = (app, props = {}, slots = {}) => {};
const data = {};
export { TestPlugin, data };
```

```
import { createApp } from 'vue';
import App from './App.vue';

import { VueLoading } from 'vue-loading-overlay';
import { TestPlugin } from './TestPlugin';

const app = createApp(App);

app.use(VueLoading);
app.use(TestPlugin);

app.mount('#app');
```

**Comment by ankurk91** [comment]
Your code indicate that you did not follow documentation
