### ISSUE TITLE
Cannot read properties of null (reading 'isCE') (Laravel VITE) app

### ISSUE THREAD

**Issue by shubham11196** [ankurk91/vue-loading-overlay#121]
Tell about your platform**
* Vue.js version : 3.2
* This package version: 6.0.3
* Laravel 10
* Vite + Vue

**Current behavior**
When I am importing loading component in my vue file.
like this 
```
import Loading from 'vue-loading-overlay';
import 'vue-loading-overlay/dist/css/index.css';
```
on VITE build running `npm run dev` 
It it throwing following error.

```
runtime-core.cjs.js:2948 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')
    at renderSlot (runtime-core.cjs.js:2948:32)
    at Proxy.<anonymous> (index.js:162:172)
    at Proxy.<anonymous> (runtime-core.cjs.js:2157:72)
    at renderComponentRoot (runtime-core.esm-bundler.js:876:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5997:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:176:19)
    at instance.update (runtime-core.esm-bundler.js:6128:16)
    at setupRenderEffect (runtime-core.esm-bundler.js:6138:5)
    at mountComponent (runtime-core.esm-bundler.js:5906:7)
    at processComponent (runtime-core.esm-bundler.js:5860:9)
```
I think it is related to slot error

**Comment by ankurk91** [comment]
The information you provided is not helpful

**Comment by shubham11196** [comment]
> 

I am rediting the issue.

**Comment by ankurk91** [comment]
Sorry it is still not enough

**Comment by halilcanadeo** [comment]
> Tell about your platform**
> 
> * Vue.js version : 3.2
> * This package version: 6.0.3
> * Laravel 10
> * Vite + Vue
> 
> **Current behavior** When I am importing loading component in my vue file. like this
> 
> ```
> import Loading from 'vue-loading-overlay';
> import 'vue-loading-overlay/dist/css/index.css';
> ```
> 
> on VITE build running `npm run dev` It it throwing following error.
> 
> ```
> runtime-core.cjs.js:2948 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')
>     at renderSlot (runtime-core.cjs.js:2948:32)
>     at Proxy.<anonymous> (index.js:162:172)
>     at Proxy.<anonymous> (runtime-core.cjs.js:2157:72)
>     at renderComponentRoot (runtime-core.esm-bundler.js:876:16)
>     at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5997:46)
>     at ReactiveEffect.run (reactivity.esm-bundler.js:176:19)
>     at instance.update (runtime-core.esm-bundler.js:6128:16)
>     at setupRenderEffect (runtime-core.esm-bundler.js:6138:5)
>     at mountComponent (runtime-core.esm-bundler.js:5906:7)
>     at processComponent (runtime-core.esm-bundler.js:5860:9)
> ```
> 
> I think it is related to slot error

Hello, I have the same problem, did you solve it?

**Comment by ankurk91** [comment]
I could not reproduce this issue on latest laravel 10.x

Please create a repo and share
