### ISSUE TITLE
Different tab infinite loading issue

### ISSUE THREAD

**Issue by Ischafak** [ankurk91/vue-loading-overlay#124]
**I'm submitting a ...**  (check one with "x")

```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

*  Nuxt.js version : 3.10.2
* Browser name and version : Chrome
* This package version : 6.0.4

**Current behavior**
There is a weird bug i encounter.
normally when the site loads i make loading active;

```
<Loading
      :active="isLoading"
      :is-full-page="true"
      background-color="#b1b3b1"
      :enforce-focus="true"
      class="main-overlay"
    >
      <div>
        <Lottie />
      </div>
    </Loading>

import { mapStores } from 'pinia'
computed: {
isLoading () {
      if (this.loadingStore) {
        console.log(this.loadingStore?.$state?.isAppLoading)
        console.log(this.loadingStore?.$state?.isLoading)
        return this.loadingStore?.$state?.isAppLoading || this.loadingStore?.$state?.isLoading
      }
      return false
    },
...mapStores(useLoadingStore, useStore, useSharedStore),
}
```

something like this normally when i am on the websites chrome tab when loading finishes there is no error(loading finishes etc). But if i am on a different tab or screen loading goes infinite even the  isLoading data false.

what can i do

**Expected behavior**
The loading must be stoped when i am on a different page when endpoint returns

**Comment by AlexUjica23** [comment]
Any news about this issue?

**Comment by Ischafak** [comment]
i stil have the problem for 6.0.6 btw
