### ISSUE TITLE
TypeError: Cannot read property 'show' of undefined

### ISSUE THREAD

**Issue by xlordt** [ankurk91/vue-loading-overlay#19]
Hi, let me start off by saying great work. 
Anyways, I am new to Vuejs and currently I an using vue with Laravel (Yes I know this has nothing to do with Laravel). My question is, how can I make this be called globally so that I don't have to import this into every single component. Currently in app.js I have

```js
//Import Vue Loading Overlay
import Loader from 'vue-loading-overlay';

// Import stylesheet
import 'vue-loading-overlay/dist/vue-loading.min.css';

Vue.use(Vuex, Loader);

const app = new Vue({
    el: '#app',
    router,
    store,
    Loader,
});
```

and in my checkout.vue, I have...

 ```js
 postToServer: function () {

            let loader = this.$loading.show({
                container: this.fullPage ? null : this.$refs.paymentForm
            });

            this.$http.post('api/validateData?cartId=' + localStorage.getItem('cartId'), this.form)

                .then(results => {

                    window.location.href = '/thankyou?cartId=' + localStorage.getItem('cartId');
                    loader.hide();

                })

                .catch(results => {

                    this.errors = [];

                     if (results.status === 422) {

                         this.errors = results.body.errors;
                         loader.hide();
                     }

                     window.scrollTo(0,0);
                });
        },
```

but I keep getting the following error.

> app.js:59499 Uncaught (in promise) TypeError: Cannot read property 'show' of undefined
>     at VueComponent.postToServer (app.js:59499)
>     at app.js:59540

so I was wondering if anyone can shed some light in the matter. 

Thanks.

**Comment by ankurk91** [comment]
You should use ES6 syntax here
```js
// This is ES5 syntax
postToServer: function () {
```
```js
// This is ES6 syntax
postToServer () {

```

**Comment by xlordt** [comment]
> You should use ES6 syntax here
> 
> ```js
> // This is ES5 syntax
> postToServer: function () {
> ```
> 
> ```js
> // This is ES6 syntax
> postToServer () {
> ```

Great! thanks for the suggestion, changed.. however still same error... maybe I am just not loading it correctly..

**Comment by xlordt** [comment]
Perfect.. that worked! Thank you.
