### ISSUE TITLE
Types declaration file for typescript

### ISSUE THREAD

**Issue by AyushG3112** [ankurk91/vue-loading-overlay#2]
In my app, when I do

`import Loading from 'vue-loading-overlay';`

I get the error:

> Could not find a declaration file for module 'vue-loading-overlay'. '/home/ayush/Desktop/currycoins/head-vue/node_modules/vue-loading-overlay/dist/vue-loading.min.js' implicitly has an 'any' type.
> 
>   Try `npm install @types/vue-loading-overlay` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-loading-overlay';`

I tried

`npm i --save @types/vue-loading-overlay`  but got the error:

> npm ERR! code E404
> npm ERR! 404 Not Found: @types/vue-loading-overlay@latest
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/ayush/.npm/_logs/2018-03-08T03_30_04_370Z-debug.log

Any chance we can have a types declaration file?

**Comment by ankurk91** [comment]
I have no plans to learn or support type script.  Sorry.

**Comment by ankurk91** [comment]
Nope, if you open a PR, i wont be able to review it, because i don't even know the syntax.
Typescript is completely new to me. 
Feel free to fork this repo, re-publish on npm and maintain it according to your needs.

**Comment by mcsky** [comment]
At least the typescript definition to describe the API of the library could be cool.

Vuejs 3 now support typescript :)

**Comment by ankurk91** [comment]
Create a DefinitelyTyped package

http://definitelytyped.org/guides/creating.html

I will link back in readme

**Comment by Elzor** [comment]
I think there is no issue with vue-loading-overlay in TS projects. 
I've just created `shims-loading.d.ts`:
``` typescript
declare module "vue-loading-overlay";
```
Then I've included vue-loading in `main.ts`:
``` typescript
import Loading from "vue-loading-overlay";
import "vue-loading-overlay/dist/vue-loading.css";

Vue.use(Loading);
Vue.component("loading", Loading);
```
And without troubles I use vue-loading-overlay in my components:
```
<loading
      :active="!SocketConnected"
      :opacity="0.8"
      loader="bars"
      :can-cancel="false"
      :is-full-page="true"
    ></loading>
```
