### ISSUE TITLE
Use in a bootstrap modal? 

### ISSUE THREAD

**Issue by devzero0** [ankurk91/vue-loading-overlay#22]
First off, thanks for putting this together and especially for the great documentation. Do you have any suggestions on how to use this from within a Bootstrap 4 modal? I'm finding that it dims and presents the spinner underneath the modal. Thanks.

**Comment by ankurk91** [comment]
So you want to cover whole screen including modal?
Sounds like it is z-index issue.
You can override the z-index via your own css.
Right now the z-index is set to 999 

https://github.com/ankurk91/vue-loading-overlay/blob/142686db8e8505d7a17ccbc216ac9ca0284a637d/src/css/index.css#L19

I will post back a working example soon.

**Comment by ankurk91** [comment]
here is the working example
https://jsfiddle.net/w8y8k5wo/691/

You just need to override the z-index value to greater than bootstrap.
```css
.vld-overlay.is-full-page {
    z-index: 1051 !important;
}
```
Feel free to re-open.

**Comment by devzero0** [comment]
Worked perfectly, thanks!
