### ISSUE TITLE
Center the loader when using before or after slot

### ISSUE THREAD

**Issue by devzero0** [ankurk91/vue-loading-overlay#23]
First off, thanks for this great component! When using the before or after slots, the loader is left aligned with the text. How can it be re-centered on screen? [Here is an example JSFiddle that shows the issue.](https://jsfiddle.net/8pu0wsL5/)

**Comment by ankurk91** [comment]
Usually, You should handle the CSS for your html. But I will still check your fiddle in my morning

**Comment by ankurk91** [comment]
Here is the updated fiddle -
https://jsfiddle.net/8pu0wsL5/4/

Check the css section.

**Comment by devzero0** [comment]
That worked, appreciate your help.

**Comment by MohamedHana** [comment]
`
.vld-icon: {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
}
`

This should be default styles for the container. Please update it if possible in the next release.
