### ISSUE TITLE
Container prop not working

### ISSUE THREAD

**Issue by fgzetech** [ankurk91/vue-loading-overlay#24]
Hi, i'm using this library but I have a problem with container property.
I assigned the container prop to a div that is the same of my `el` vue instance property (I want to view the top menu always) and didn't work.
I followed your examples and I also change the ref div but didn't work.

**Comment by straightupjac** [comment]
Hi @ankurk91 
I am still having this issue. The way I am using it is as follows:
```
  <div
    class="vld-parent"
    style="position: relative;"
  >
    <v-card
      ref="chainStatusCard"
      elevation="0"
      class="rounded-xl secondary vld-parent"
    >
   ...
   </ v-card>
</div>
```

and for toggle loader
```
toggleLoader(toggle) {
      if (toggle) {
        if (this.loader) {
          return;
        }
        const container = this.$refs.chainStatusCard;
        this.loader = this.$loading.show({ container });
      } else {
        if (this.loader) {
          this.loader.hide();
        }
        this.loader = null;
      }
```

**Comment by ankurk91** [comment]
@straightupjac 

Please create an new issue, fill-up the issue template, create re-production on js-fiddle or similar.
