### ISSUE TITLE
Cannot use it inside an element full screen error

### ISSUE THREAD

**Issue by hamzaali00001** [ankurk91/vue-loading-overlay#25]
I want to show this loader inside a div element but it always goes full screen. I do not what's the problem or its a bug.

I placed vld-parent class on the div and a ref. Then I am using this code initiate, but it goes full screen.

```js
let loader = this.$loading.show({
    container: this.$refs.loadContainer,
    loader: this.loader,
}, {});

setTimeout(() => {
    loader.hide()
},5000)
```

I am using it as a plugin.

Please Help me I am stuck.

**Comment by ankurk91** [comment]
How did you come up with this 
```
loader: this.loader,
```
The loader prop documentation says 
```
Name of icon shape you want use as loader, spinner or dots or bars
```

**Comment by ankurk91** [comment]
Readme has everything you need, there is an examples folder too.

i wish if you could share a minimal setup to demonstrate your issue.
You can start from here

https://codesandbox.io/s/8kxvyky152

**Comment by hamzaali00001** [comment]
Ok, it worked. Thanks. But can you please tell me on multiple images. Basically, I want to use it as a loader while the images are loading (deferring images) to speed up page time.

**Comment by ankurk91** [comment]
Use it as a component
