### ISSUE TITLE
Automatize Ajax requests

### ISSUE THREAD

**Issue by taianrj** [ankurk91/vue-loading-overlay#27]
Hello, Ankur!

It's not a issue, just a question. Could you help me?

Is there an easy way to show your component everytime an ajax request is started and hide it everytime an ajax request is completed?

**Comment by ankurk91** [comment]
If you are using library like `axios`, then yes.
You can axios intercepters.

**Comment by taianrj** [comment]
Thank you for the fast answer. I'm trying to use jquery ajax interception to achieve it and I'm doing it to start and it's working, but it's creating many instances of the component (one overlaping the other).

How to avoid it?

`$(function () {
			$.ajaxSetup({
				beforeSend: function () {
					loader = self.$loading.show();
				}
			});
		});`

**Comment by ankurk91** [comment]
You have to store instance in a variable, then hide the loader if instance exists, make a new instance, store it in same variable.

This a simple programming issue.

**Comment by taianrj** [comment]
Thank you! Your component is amazing!
