### ISSUE TITLE
How to hide the loader using API way?

### ISSUE THREAD

**Issue by patrickyue** [ankurk91/vue-loading-overlay#29]
Vue.$loading.hide() is not working...

**Comment by ankurk91** [comment]
The read me file has everything you need.

**Comment by alignwebs** [comment]
@ankurk91  I am also facing the same issue, documentation has just simple `loader.hide()` 

@patrickyue were you able to solve this bro ?

**Comment by ankurk91** [comment]
```
let loader = Vue.$loading.show() 
loader.hide()
```

Readme has everything

**Comment by alignwebs** [comment]
the problem is with axios interceptor, duplicate https://github.com/ankurk91/vue-loading-overlay/issues/7

`let loader` variable can not be used in different scope as multiple axios request overrides the `loader` variable leaving the previously created `loader` opened

**Comment by ankurk91** [comment]
It is simple programming problem, not related to this plugin.

You can manage your application state in your way.

**Comment by alignwebs** [comment]
It will be a great help if you could post a working example of loader hide using Axios request and response interceptor. Thanks

**Comment by patrickyue** [comment]
> @ankurk91 I am also facing the same issue, documentation has just simple `loader.hide()`
> 
> @patrickyue were you able to solve this bro ?

Sorry, this plugin is not working with axios,
and I just used some own css to build my own loading stuff.
