### ISSUE TITLE
Fix the loader position

### ISSUE THREAD

**Issue by aliraza371** [ankurk91/vue-loading-overlay#31]
Hello,

Thanks for the package.

I want to how can I fix the loader position, as I'm using the loader on two tables, The loader position varies by number content in a table, How I can assure that the spinner always be on top. Just like when there is no content in table. 

Looking forward to your reply on this.

Thanks

**Comment by ankurk91** [comment]
You can always override the css.
It is using flex box.
https://github.com/ankurk91/vue-loading-overlay/blob/master/src/css/index.css

The loader is being place center of its container by default.
I would suggest to update container to have a min height.
