### ISSUE TITLE
example without webpack

### ISSUE THREAD

**Issue by doomiris** [ankurk91/vue-loading-overlay#33]
could you please make a full example without webpack?
```
<!-- Vue js -->
<script src="https://cdn.jsdelivr.net/npm/vue@2.5/dist/vue.min.js"></script>
<!-- Lastly add this package -->
<script src="https://cdn.jsdelivr.net/npm/vue-loading-overlay@2"></script>
<link href="https://cdn.jsdelivr.net/npm/vue-loading-overlay@2/dist/vue-loading.min.css" rel="stylesheet">
<!-- Init the plugin and component-->
<script>
Vue.use(VueLoading);
Vue.component('loading', VueLoading)
</script>
```

**Comment by ankurk91** [comment]
Do you know how to use vue.js without webpack? If yes, then you should be able to use this package too.

API is same for both. Readme file has everything you need.

I think you missed the js fiddle link in readme
https://jsfiddle.net/ankurk91/w8y8k5wo/

**Comment by doomiris** [comment]
sorry to trouble, but jsfiddle.net is blocked in my country >,<
I'm beginner of vue, should I put a `<vue-loading-overlay></vue-loading-overlay>` somewhere?
or add some options when create vue?
```
var ParaApp = new Vue({
      el: '#vueApp',
      i18n, 
      data: {        
      },
      methods: { }
})
```
