### ISSUE TITLE
animatetransform with Edge 18 is not animating

### ISSUE THREAD

**Issue by AleeeKoi** [ankurk91/vue-loading-overlay#36]
Hello,
As mentioned in readme edge 18 should be supported.
But SVG "animatetransform" is not supported yet by Edge.
Any suggestions?
Thank you

**Comment by AleeeKoi** [comment]
@ankurk91 it's the svg element that is not supported. See this:
https://caniuse.com/#feat=mdn-api_svganimatetransformelement

**Comment by ankurk91** [comment]
Okay, i will look into it. Meanwhile you can tey a different loader other than spinner.

**Comment by AleeeKoi** [comment]
Hi @ankurk91 , same problem with all loaders.
I think that migrate all svg loaders to html+css animations could be a great solution.
Thank you

**Comment by ankurk91** [comment]
Switching to html+css is not possible now.
V2 was using this approach.
You can try v2.
