### ISSUE TITLE
z-index default only set on full page overlay

### ISSUE THREAD

**Issue by Relequestual** [ankurk91/vue-loading-overlay#41]
I noticed that when using the non full page version, the default z-index is 1.
This confused me a little, but I was able to provide a higher number as a prop.

This could be fixed by changing the CSS or adding a default value for the prop.
I guess the correct fix would be to increase the default value in the CSS.

If you're happy with that solution, I'm happy to submit a PR.

**Comment by ankurk91** [comment]
What should be default `z-index` ?
Bootstrap css has `1050` for modals.

**Comment by Relequestual** [comment]
My feeling would be to make a loading overlay higher.
Default of `9999` seems reasonable because it's clear it should always be the top.

**Comment by ankurk91** [comment]
I will check various other css frameworks and similar libraries, make decision then.

**Comment by Relequestual** [comment]
I thought 9999 to start with, and then confirmed by looking at https://css-tricks.com/rational-z-index-values/ - A rational value.

**Comment by ankurk91** [comment]
Should be fixed in v3.3.0
