### ISSUE TITLE
Set Loader Options when using as Plugin

### ISSUE THREAD

**Issue by bluezald** [ankurk91/vue-loading-overlay#43]
Can we use the loader to set its global options when installing as plugin, like this:
```
Vue.use(Loading, {
  container: null,
  isFullPage: true,
  loader: 'dots'
})
```
so that when I call it, I can do this 
```
this.$loading.show()
```
instead of
```
let loader = this.$loading.show({
      container: null,
      isFullPage: true,
      loader: 'dots'
    })
```

**Comment by ankurk91** [comment]
The readme has everything you need.

https://github.com/ankurk91/vue-loading-overlay#global-configs

**Comment by YusufcanY** [comment]
When i use as plugin in Vue 3.2.24, I can't set global config for plugin,
```
app.use(VueLoading,{
    color: 'red',
    backgroundColor: '#f8f8',
    lockScroll: true,
});
```
But when define props in where I calling show function it works, how this happening?

**Comment by ankurk91** [comment]
you can not expect global config when using it via composition api

**Comment by YusufcanY** [comment]
yea i got that thanks for the time
