### ISSUE TITLE
 ERROR  render function or template not defined in component: loading

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [ankurk91/vue-loading-overlay#46]
This is the error that I am receiving on my latest pull of version 3.2.0 with NuxtJS.

Take note that 1 week ago it is working fine but 5 hours earlier where my automated build `npm install` a new one `vue-loading-overlay` package this occurred.

**Comment by ankurk91** [comment]
I will try to reproduce this.

**Comment by ankurk91** [comment]
It is annoying to see this error.
It is working fine till version 3.3.0, but broken in version 3.3.1.

Something is wrong in webpack configs.
Need to debug more.

**Comment by ankurk91** [comment]
Should be fixed in v3.3.2

Tested here
https://codesandbox.io/s/nuxt-vue-xdvgm
