### ISSUE TITLE
 Expected Number with value NaN, got String with value "200".

### ISSUE THREAD

**Issue by shijiezhou1** [ankurk91/vue-loading-overlay#48]
vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: type check failed for prop "width". Expected Number with value NaN, got String with value "200".

found in

---> <VueLoading>
       <Post> at src/views/Post.vue
         <App> at src/App.vue
           <Root>

**Comment by ankurk91** [comment]
Hey, can you please provide more info, looks like your prop validation failed.

**Comment by shijiezhou1** [comment]
When I set the width, it does not work and I provide `width=200`. It's still not working.

**Comment by ankurk91** [comment]
This was not helpful, please share a code snippet .
