### ISSUE TITLE
Add TypeScript definitions.

### ISSUE THREAD

**Issue by jbenner-radham** [ankurk91/vue-loading-overlay#5]
Would you be interested in adding TypeScript definitions to the project? I've actually got them mostly written for a project I'm working on that uses this plugin so I could provide a merge request to implement them if that's cool.

P.S. Thanks for providing an awesome plugin.

**Comment by ankurk91** [comment]
@jbenner-radham 
I have no plans to support/learn type script.
Feel free to publish those definitions as a separate package. I will reference that package in my readme.
