### ISSUE TITLE
Lock scroll

### ISSUE THREAD

**Issue by ryanmwc** [ankurk91/vue-loading-overlay#51]
When the loading spinner is active, I can still scroll down the page. How do I prevent this?

**Comment by ankurk91** [comment]
Sadly this feature is not available, i you have any reference to implement this, let me know.

**Comment by ryanmwc** [comment]
I think you just have to target the `body` and/or `html` tags with vanilla JS, add a class, and lock the scrolling with some CSS. Plenty of stuff on Stackoverflow should have the styling you need to lock the scroll bar.  And then when the loading spinner is inactive, just remove the class.

I suggest this because I know that Bootstrap-Vue locks the scrollbar when you open a [modal](https://bootstrap-vue.org/docs/components/modal) even though the component exists within a Vue instance.  So there has to be a way.

**Comment by ankurk91** [comment]
I will look into it.

**Comment by ankurk91** [comment]
Has been added in v3.4.0

**Comment by HlaingMinThan** [comment]
i can't still use lock scroll :( @ankurk91

**Comment by ankurk91** [comment]
@HlaingMinThan
It is not my problem
