### ISSUE TITLE
Setting isFullPage: false as default doesnt work

### ISSUE THREAD

**Issue by outluch** [ankurk91/vue-loading-overlay#52]
```
Vue.use(Loading, {
  isFullPage: false,
})
```

I init plugin like that, but it works as fullscreen until I specify `:is-full-page="false"`.

**Comment by ankurk91** [comment]
When you set `isFullPage` to `false` you suppose to supply the `container` prop.
See example

https://jsfiddle.net/ob2v5dy0/1/
