### ISSUE TITLE
Full page bug

### ISSUE THREAD

**Issue by rogerclaus** [ankurk91/vue-loading-overlay#53]
Hi. I'm building a SPA. I made some tests with your component some weeks ago, but had to switch to another one because, strangely, I was not able to set it full page, the navbar would still appear no matter what.

Long story short, I gave up on that design and ended up not using that other component either. However, now I have another demand in which your component with that particular behavior would be perfect, but it's gone. Now that I'm testing your component again, it is hiding everything on my page, including the navbar.

Do you know how can I get that behavior again, in which the navbar (set in App.vue) is not hidden?

Thanks for your time and your awesome component.

**Comment by ankurk91** [comment]
You navbar was visible on full screen loading, this might be because of z-index issue, try to increase the z-index on loading overlay and it should work fine.

**Comment by rogerclaus** [comment]
I generally avoid touching z-index, and didn't do so since the last time I used your component. I was expecting a solution in which I could restrict the overlay to a div, but I can along with changing the z-index. Thanks.
