### ISSUE TITLE
How to global config for default slot?

### ISSUE THREAD

**Issue by rogerluo410** [ankurk91/vue-loading-overlay#54]
> Vue.use( 
    Loading,
   {
    // props
   }
  // {
  //   // slots
  //   default: this.$createElement("loading-img")
  // }
);

As we know, we can't use  this.$createElement method in Vue.use(), How can we config default slot globally? thank you!

**Comment by ankurk91** [comment]
You can do it like:

```js
const custom = Vue.extend({
  template: `<h3 class="custom">loading</h3>`
});

Vue.component('custom-loader', custom);

Vue.use(VueLoading, {
  // options
} , {
  // slots
   default: (new Vue()).$createElement('custom-loader')
});
```

https://jsfiddle.net/L10q7daz/1/
