### ISSUE TITLE
How to manually show it?

### ISSUE THREAD

**Issue by aswzen** [ankurk91/vue-loading-overlay#56]
To hide we are using hide(), but for show() what should i do?

**Comment by ankurk91** [comment]
Readme has everything

https://github.com/ankurk91/vue-loading-overlay#as-plugin

**Comment by haposan06** [comment]
I think he asked about how to show it using the reference. To show in initial stage using
`let loader = this.$loading.show({`
Then using loader, we can hide by loader.hide(), but how to show it again using that loader variable?

**Comment by aswzen** [comment]
> I think he asked about how to show it using the reference. To show in initial stage using
> `let loader = this.$loading.show({`
> Then using loader, we can hide by loader.hide(), but how to show it again using that loader variable?

Yeah that what i am asking for, i didnt see it anywhere on the readme..
