### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by mits87** [ankurk91/vue-loading-overlay#66]
Hi,
can you add a support for VUE 3?
Thank you in advance.

**Comment by Matthewloughton** [comment]
+1

**Comment by ankurk91** [comment]
Made some progress on [next](https://github.com/ankurk91/vue-loading-overlay/tree/next) branch.

It is not easy upgrade :)

**Comment by HakobiDev** [comment]
+1 Hopefully it works for Vue 3

**Comment by Machigatta** [comment]
+1 would like to use it, instead of having to build something myself

**Comment by cyberco** [comment]
+1 Especially since there seems no alternative for Vue 3 (not even a simple spinner).

**Comment by ankurk91** [comment]
I have significant progress on [next](https://github.com/ankurk91/vue-loading-overlay/tree/next) branch. :rocket:

You can expect a beta version soon.

Next todo

* [ ] Update readme, usage guide
* [ ] Add upgrade guide
* [ ] Update test case
* [ ] Update type defs
* [ ] Manual testing 
* [ ] Upgrade to Webpack 5

Thanks for your patience.

**Comment by ankurk91** [comment]
You can try the latest beta now 
```
yarn add vue-loading-overlay@^4.0
```
Check [next](https://github.com/ankurk91/vue-loading-overlay/tree/next) branch for docs

**Comment by yuanzhian** [comment]
Rocket speed

**Comment by zeyadsharo** [comment]
@ankurk91  does support Composition API Vuejs 3?

**Comment by ankurk91** [comment]
@zeyadsharo 
Undocumented yes

https://github.com/ankurk91/vue-loading-overlay/blob/master/src/js/api.js#L4
