### ISSUE TITLE
What format should i use for default?

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [ankurk91/vue-loading-overlay#68]
Should i load my own animation using GIF, SVG? What format should i use?

**Comment by ankurk91** [comment]
This package comes with 3 different loader, those are inbuilt, no extra code required.
You can play with them on demo page. 

If you want to load your own loader, you can do it via slots. 

You can supply your own html into slot. 
It can be anything, svg or GIF. 

You need take care of styling by your own.
