### ISSUE TITLE
Axios interceptor

### ISSUE THREAD

**Issue by pirmax** [ankurk91/vue-loading-overlay#7]
I've need to use Axios and your plugin, but if I add the start of vue-loading-overlay when I have a request with Axios, I muse have the variable of loader...

Could you separate the instance of $loading ?

With this, I can use this.$loading.show() when I want display the loader overlay.
And I can use this.$loading.hide() when the request is executed.

Thanks.

**Comment by ankurk91** [comment]
Is this helpful.

```js
// store loader instance in external variable
var loader = null;

window.axios.interceptors.request.use(
  (config) => {
   // show loader
   loader this.$loading.show()
    return config
  },
  (error) => {
    return Promise.reject(error);
  }
);

// shared method 
function hideLoader(){
 loader && loader.hide();
  loader = null;
}

// Intercept all responses
window.axios.interceptors.response.use(
  (response) => {
    // hide loader
    hideLoader()    
    return response;
  },

  (error) => {
    // hide loader
   hideLoader()
    return Promise.reject(error);
  }
);
```

**Comment by ankurk91** [comment]
Closing, feel free to  re-open

**Comment by elahekaramzade** [comment]
I try this but loading never hide , will show for ever

**Comment by egidar** [comment]
let loader = null;

    function hideLoader() {
      loader && loader.hide();
      loader = null;
    }

    axios.interceptors.request.use(
      (config) => {
        if (loader) return config;
        loader = Vue.$loading.show();
        return config;
      },
      (error) => {
        return Promise.reject(error);
      },
    );

    axios.interceptors.response.use(
      (response) => {
        hideLoader();
        return response;
      },
      (error) => {
        hideLoader();
        return Promise.reject(error);
      },
    );
  },

**Comment by olufemioyedepo** [comment]
This works for me @egidar
