### ISSUE TITLE
Support for hiding loader after all promises are done

### ISSUE THREAD

**Issue by abhion** [ankurk91/vue-loading-overlay#70]
If there are multiple ajax calls that call the show(), then if any one of the ajax call is done and calls hide after the response, the loader is hidden but an ajax call is still not done.

It could be like
`<vue-loader :showLoading="loadCount === 0 ? false : true"> 
    <App />
</vue-loader>`

In every ajax call I can do `this.loadCount++`, and when it's done, I can do `this.loadCount--` so when all the calls are done loadCount will be 0 and loader will be hidden only when all are done.

**Comment by ankurk91** [comment]
You can manage this in your code base.
