### ISSUE TITLE
Using without packer

### ISSUE THREAD

**Issue by TomHeckl** [ankurk91/vue-loading-overlay#75]
Hi,
is it possible to use the component without webpacker etc.?

Best regards
Tom

**Comment by ankurk91** [comment]
The instructions are already in readme
```html
<!-- Vue js -->
<script src="https://cdn.jsdelivr.net/npm/vue@2.6"></script>
<!-- Lastly add this package -->
<script src="https://cdn.jsdelivr.net/npm/vue-loading-overlay@3"></script>
<link href="https://cdn.jsdelivr.net/npm/vue-loading-overlay@3/dist/vue-loading.css" rel="stylesheet">
<!-- Init the plugin and component-->
<script>
Vue.use(VueLoading);
Vue.component('loading', VueLoading)
</script>
```

**Comment by TomHeckl** [comment]
Thanks you for your quick reply and help….

 

Tom Heckl

www.tomheckl.de

 

Von: Ankur Kumar <notifications@github.com> 
Gesendet: Montag, 1. März 2021 08:43
An: ankurk91/vue-loading-overlay <vue-loading-overlay@noreply.github.com>
Cc: TomHeckl <thomas.heckl@kabelmail.de>; Author <author@noreply.github.com>
Betreff: Re: [ankurk91/vue-loading-overlay] Using without packer (#75)

 

The instructions are already in readme


<script src="https://cdn.jsdelivr.net/npm/vue@2.6"></script>

<script src="https://cdn.jsdelivr.net/npm/vue-loading-overlay@3"></script>
<link href="https://cdn.jsdelivr.net/npm/vue-loading-overlay@3/dist/vue-loading.css" rel="stylesheet">

<script>
Vue.use(VueLoading);
Vue.component('loading', VueLoading)
</script>
