### ISSUE TITLE
Css not loading prod build

### ISSUE THREAD

**Issue by peterson-umoke** [ankurk91/vue-loading-overlay#76]
hello, i am currently using your component in an inertiajs environment, but it seems to skip the css import when i am building for prod.. do you have an scss version available

**Comment by ankurk91** [comment]
I am not what kind of issue you are facing, it is most likely the tooling issue, this package comes with a single css file that you need to import, you can check the source code, there is no scss.

i would suggest to stop using inertiajs.js and back to regular website development. :)

**Comment by peterson-umoke** [comment]
no problem chief
