### ISSUE TITLE
Uncaught TypeError: Cannot set property '$loading' of undefined

### ISSUE THREAD

**Issue by yuanzhian** [ankurk91/vue-loading-overlay#77]
Uncaught TypeError: Cannot set property '$loading' of undefined

**Comment by ankurk91** [comment]
Please share a minimal re-production of code.
+
Fill the issue template too

**Comment by yuanzhian** [comment]
Using vue3.0

**Comment by ankurk91** [comment]
This package does not support vue 3 yet.

Will be releasing a new version soon

**Comment by yuanzhian** [comment]
ok

**Comment by ankurk91** [comment]
You can try latest beta now
```
yarn add vue-loading-overlay@^4.0

npm i vue-loading-overlay@4.0.0
```

See progress at https://github.com/ankurk91/vue-loading-overlay/issues/66
