### ISSUE TITLE
Loading Spinner with a Specific image

### ISSUE THREAD

**Issue by kayaaliemre** [ankurk91/vue-loading-overlay#78]
Hello,
I could not find any props like mode: 'picture', could you think that implement this feature. May be it will be really useful. I am using your loading overlay and I would like to do like spinner in below.
More information you can check this;

https://www.cssscript.com/rotating-loading-spinner-javascript-zlataloader-js/

**Comment by ankurk91** [comment]
The component provides a slot where you can place your own html

```html
 <loading :active.sync="isLoading">
      <img src="your-image.png" class="my-image" alt="image" width="50px">
</loading>
```

Please read the docs and see example folder

**Comment by kayaaliemre** [comment]
Sorry, I could not find. :) Thank you very much
