### ISSUE TITLE
defining "after" slot in .show() method.

### ISSUE THREAD

**Issue by wiforsyth** [ankurk91/vue-loading-overlay#79]
I'm attempting to append a div with a text class to the loader icon using the "after" slot in the .show() method. I've attempted to use jquery to create the markup, but it seems that I can only append text. I've event tried to query and target the vid-icon class to append.

Documentation is sparse when attempting to do this from the javascript side versus markup. Could someone assist?

...
`        slotDefinition: {
          after: $('.vid-icon').append('<div class="loader-spinning-text">loading ...</div>')
        }`
...

`loader = Vue.$loading.show(propertiesDefinition, args.slotDefinition ? args.slotDefinition : {});`

**Comment by ankurk91** [comment]
Please fill out the issue template

**Comment by wiforsyth** [comment]
Issue Template?

**Comment by ankurk91** [comment]
But you are not new to internet

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Just google it

**Comment by wiforsyth** [comment]
I did some searching, and following this:

https://docs.github.com/en/github/managing-your-work-on-github/creating-an-issue

they said that if there are templates, then I would be presented with multiple options (step 4.)

I assure you, it takes me directly to a text area to insert the question, sans template options.

**Comment by ankurk91** [comment]
Okay, my mistake


Please specify this package version

**Comment by wiforsyth** [comment]
We're using 3.4.2. I think I mainly am just looking for an answer to what type of object the "after" slot is looking for in the .show() method. It won't take a jquery object, Do I need to create a specific element via string conversion like jquery's ".parseHTML()"?

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-loading-overlay/blob/19870761d9dbe38cffb24e352f1c4fee1b5fafa9/examples/components/plugin.vue#L93


Here is the example
