### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by vhb-Mark** [ankurk91/vue-loading-overlay#80]
**I'm submitting a ...**  (check one with "x")
```
[ x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Vue.js version : 3
* Browser name and version : Chrome on Mac
* This package version : 4

**Current behavior**
As soon as I use the following code, it will throw the error.
The value container is this.$refs.containerCompanyInfo

`let loader = this.$loading.show({
                container: container,
                //canCancel: false,
                isFullPage: false
            })`

The code is called in a watch function which is triggered in the created function.

**Comment by ankurk91** [comment]
Please share a minimal reproduction

**Comment by ankurk91** [comment]
The container prop is working fine for me

https://github.com/ankurk91/vue-loading-overlay/blob/da0c2e49f66f7032275377b15d3b918069135c1c/examples/components/pluginExample.vue#L80
