### ISSUE TITLE
Loading overlay not covering the entire page

### ISSUE THREAD

**Issue by umutdr** [ankurk91/vue-loading-overlay#87]
**I'm submitting a Question  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ x ] Other, please describe
```

**Tell about your platform**
* Vue.js version : 2.6.12
* Browser name and version : Chrome Latest
* This package version : 3.0.1

**My Question**
I'm not using the component. So I can't set the `is-full-page` prop to true. But I want to make the overlay cover the entire page. How can I do this?

Example:
![loading-overlay](https://user-images.githubusercontent.com/42785142/125606227-af4bf2ca-2db1-4242-ba4c-2b02447f0ca6.png)

**Current behavior**
Loading overlay not covering the entire page. It only covering the content, does not cover the sidebar.

**Expected behavior**
I want to make the loading overlay cover the entire page

**Minimal reproduction of the problem with instructions**
My main.js definitions:
```js
import VueLoading from 'vue-loading-overlay';
import 'vue-loading-overlay/dist/vue-loading.css';
Vue.use(VueLoading, {
  canCancel: false,
  onCancel: () => {},
  color: '#3399ff',
  loader: ['spinner', 'dots', 'bars'][1],
  width: 64,
  height: 64,
  backgroundColor: '#333333',
  opacity: 0.35,
  zIndex: 999,
});
```

And the interaction with the plugin:
```js
let loading = Vue.$loading.show();
...
loading.hide()
```

**Comment by ankurk91** [comment]
it is full screen on demo page, see
https://ankurk91.github.io/vue-loading-overlay/

you need fix your css and page layout
