### ISSUE TITLE
Vue3 - Use loader instance in store or router

### ISSUE THREAD

**Issue by webmastervinay** [ankurk91/vue-loading-overlay#92]
**This is not a issue. Its question or feature request (if not available)**

Your documentation mentions that it can be used inside any component or via composition api. Glad it support both.

I couldn't find a way where it can be used inside store or router. I tried following:

but it broke the code and showing errors in console.
* Vue.js version : 3.x
* Browser name and version : Chrome 92
* This package version : 4.x.x

**Current behavior**

```
import { useLoading} from 'vue-loading-overlay'
const $loading = useLoading()
```

![image](https://user-images.githubusercontent.com/5024049/131817525-4a6ecbbc-1100-423d-b1cf-bba3cc6fbcaa.png)

**Comment by ankurk91** [comment]
* Make sure your are using most recent version - 4.0.4
* The package is already exporting `useLoading`, it should work

Search for `useLoading` in the dist file
https://unpkg.com/browse/vue-loading-overlay@4.0.4/dist/vue-loading.js

**Comment by webmastervinay** [comment]
Yes, I am using latest version of your package but getting the same error. Tried rm -rf node_modules but could not solve.

![image](https://user-images.githubusercontent.com/5024049/131823038-ab3476e7-1b0b-4ea3-bfd0-dc948f1c1ce0.png)

There is also useLoading function available in the said file:

![image](https://user-images.githubusercontent.com/5024049/131823157-8b622d58-a6b7-415a-aff9-438baafe8648.png)

**Comment by ankurk91** [comment]
i will try this in my project and let you know soon,

**Comment by ankurk91** [comment]
This is strange, i thought i have fixed the export issue last week, but it still there.
https://github.com/ankurk91/vue-loading-overlay/issues/88

Created a fiddle to see the issue in browser
https://codesandbox.io/s/async-star-xmp65?file=/src/App.vue

**Comment by leture** [comment]
Hi,

I am also having problems with importing and using `useLoading`. During my debugging I saw that `useLoading` is in the dist file but not in `types/loading.d.ts`. Maybe this is part of the problem? I am using it in a project with TypeScript usage.

Greetings

**Comment by tbrains** [comment]
Facing the same issue,  any updates?

Thank you

**Comment by ankurk91** [comment]
I am planning to use rollup for bundling since webpack does not support named-export. There is no ETA.

**Comment by ankurk91** [comment]
Please follow this issue now
https://github.com/ankurk91/vue-loading-overlay/issues/88

**Comment by ankurk91** [comment]
This has been fixed with v5
```
npm install vue-loading-overlay@5.0.0
```
