### ISSUE TITLE
lock scroll not working on vue 2

### ISSUE THREAD

**Issue by HlaingMinThan** [ankurk91/vue-loading-overlay#93]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Vue.js version : 3.x
* Browser name and version : Chrome|Firefox|Edge x.x.x
* This package version : 4.x.x

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by HlaingMinThan** [comment]
vue js -2 
lock scroll not working

**Comment by ankurk91** [comment]
Please share a minimal reproduction, may be on codesandbox.io

**Comment by ankurk91** [comment]
This package adds a css class to body to lock scroll

https://github.com/ankurk91/vue-loading-overlay/blob/19870761d9dbe38cffb24e352f1c4fee1b5fafa9/src/css/index.css#L2

It does nothing fancy, it might possible that your own css is causing this issue
