### ISSUE TITLE
Bug: Vue3 TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by hasanparasteh** [ankurk91/vue-loading-overlay#95]
When i import the useLoading from the package I got the `TypeError: Object(...) is not a function` Error when i call the loading. look at the code at below:

```
import { useLoading } from 'vue-loading-overlay';
const loading = useLoading();
```

* Vue.js version : 3.0.0
* Browser name and version : Firefox 91.0.2
* This package version : 4.0.4

**Comment by ankurk91** [comment]
You can not import `useLoading` , it is buggy at this moment,

https://github.com/ankurk91/vue-loading-overlay/issues/92
