### ISSUE TITLE
Too much recursion error

### ISSUE THREAD

**Issue by AniaKru95** [ankurk91/vue-loading-overlay#96]
**I'm submitting a ...**  (check one with "x")
```
[ x ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Vue.js version : ^2.6.11 => 2.6.14
* Browser name and version : Chrome|Firefox|Edge x.x.x
* This package version : ^3.4.2 => 3.4.2

**Current behavior**
I use vue-loading-overlay as a component. And I use below code inside my two different components.
1. I go to page where above two components are used.
2. During the loading I go to another page (without these components)
3. Then I get an error: "too much recursion"
![obraz](https://user-images.githubusercontent.com/84393751/141086969-fe116826-3a0f-4c2d-948d-b0c9b9f52f24.png)

When I use below code only in one my component - everything works fine.

```vue
<template>
    <div class="vld-parent">
     <loading :active="isLoading"
               :color="'#3d4950'"
               :loader="'dots'"/>
    </div>
</template>
<script>
import Loading from 'vue-loading-overlay';
export default {
  name: "RankItem",
    components: {
        Loading
          },
     }
     </script>
```

**Expected behavior**
When I go to another page during the loading I don't want to get error "too much recursion".

**Comment by ankurk91** [comment]
```vue
<loading :active="isLoading"
               :color="'#3d4950'"
               :enforce-focus="false"
               :loader="'dots'"/>
```
Your example was incomplete, please provide a working example with your use-case on codesandbox

Can you to set `enforce-focus` to false ?

**Comment by AniaKru95** [comment]
Setting "enforce-focus" to "false" - worked.

I really appreciate your help :)
