### ISSUE TITLE
Is it possible to use it on a table row?

### ISSUE THREAD

**Issue by Cod3rMax** [ankurk91/vue-loading-overlay#99]
is it possible to use the loading on specific element?

**Comment by ankurk91** [comment]
I have not tried it on table row. You can play with and let me know ;)

**Comment by Cod3rMax** [comment]
yep i tried it quickly didn't seem to be working, i did put isFullPage to false and parent class to the <tr> the loader keeps loading to the full page, the problem i'm checking something so i need each row to be checked with axios request stay loading untill it finish

**Comment by ankurk91** [comment]
Please share minimal code that represent your issue.

May be on jsfiddle.net

BTW, did you read the docs well? 


When is-full-page is set to false, the container element should be positioned as position: relative. You can use CSS helper class vld-parent.

**Comment by Cod3rMax** [comment]
the problem the code is too long but look, it did work however when i put the ref to the table row and i use v-for it doesn't work i think each table row or td needs a unique ref?

**Comment by ankurk91** [comment]
Yes
